FROM oven/bun

WORKDIR /app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages/db/package.json ./packages/db/package.json
COPY ./packages/common/package.json ./packages/common/package.json
COPY ./apps/http-backend/package.json ./apps/http-backend/package.json

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

RUN bun install

EXPOSE 3002

RUN cd packages/db && bunx prisma generate

CMD ["bun", "run", "--cwd", "apps/http-backend", "index.ts"]